// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_ninja_apprentice = "CgkI5fOH1boJEAIQAg"; // <GPGSID>
        public const string achievement_beat_them_all = "CgkI5fOH1boJEAIQAw"; // <GPGSID>
        public const string leaderboard_score = "CgkI5fOH1boJEAIQAQ"; // <GPGSID>
        public const string achievement_cheapskate = "CgkI5fOH1boJEAIQBw"; // <GPGSID>
        public const string achievement_slayer = "CgkI5fOH1boJEAIQBA"; // <GPGSID>
        public const string achievement_beginner_runner = "CgkI5fOH1boJEAIQBg"; // <GPGSID>
        public const string achievement_ninja_model = "CgkI5fOH1boJEAIQBQ"; // <GPGSID>

}

